name: Builds

on: [pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: get submodules
        shell: bash
        run: git submodule update --init --recursive

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: install SDL2
        shell: bash
        run: sudo apt-get install libsdl2-dev

      - name: install mesa-common-dev
        shell: bash
        run: sudo apt install mesa-common-dev

      - name: Configure CMake
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER="/usr/bin/clang" -DCMAKE_CXX_COMPILER="/usr/bin/clang++"

      - name: build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE


  build-emscripten:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install Emscipten
        run: |
          wget -q https://github.com/emscripten-core/emsdk/archive/master.tar.gz
          tar -xvf master.tar.gz
          emsdk-master/emsdk update
          emsdk-master/emsdk install latest
          emsdk-master/emsdk activate latest

      - name: Build
        run: |
          pushd emsdk-master
          source ./emsdk_env.sh
